const ItemList = [
    {
        id: 1,
        callItem: "cook",
        image: "images/1.webp",
        admin: "Admin",
        time: "2min",
        date: "7 july",
        title: "Cooking With the kids",
        description: "Create a blog post subtitle that summerizes your post in a few short, punchy sentences and ...",
        views: "200",
        comments: "2",
        hearts: "5",
    },
    {
        id: 2,
        callItem: "cook",
        image: "images/2.webp",
        admin: "Admin",
        time: "5min",
        date: "17 july",
        title: "Rainy day painting",
        description: "Create a blog post subtitle that summerizes your post in a few short, punchy sentences and ...",
        views: "2110",
        comments: "12",
        hearts: "51",
    },
    {
        callItem: "cook",
        id: 3,
        image: "images/3.webp",
        admin: "Admin",
        time: "44min",
        date: "7 Aug",
        title: "kids Room Remodel",
        description: "Create a blog post subtitle that summerizes your post in a few short, punchy sentences and ...",
        views: "300",
        comments: "222",
        hearts: "511",
    },
    {
        id: 4,
        callItem: "food",
        image: "images/4.webp",
        admin: "Admin",
        time: "2min",
        date: "7 july",
        title: "Meet Our Family ",
        description: "Create a blog post subtitle that summerizes your post in a few short, punchy sentences and ...",
        views: "200",
        comments: "2",
        hearts: "5",
    },
    {
        id: 5,
        callItem: "food",
        image: "images/5.webp",
        admin: "Admin",
        time: "2min",
        date: "7 july",
        title: "A day at the zoo",
        description: "Create a blog post subtitle that summerizes your post in a few short, punchy sentences and ...",
        views: "200",
        comments: "2",
        hearts: "5",
    },
    {
        id: 6,
        callItem: "food",
        image: "images/6.webp",
        admin: "Admin",
        time: "2min",
        date: "7 july",
        title: "Summer saturday activities",
        description: "Create a blog post subtitle that summerizes your post in a few short, punchy sentences and ...",
        views: "200",
        comments: "2",
        hearts: "5",
    },
];
export default ItemList